# Generated by Django 4.0.1 on 2022-01-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=100)),
                ('lname', models.CharField(blank=True, max_length=100)),
                ('std_id', models.CharField(blank=True, max_length=10)),
                ('contact_no', models.CharField(blank=True, max_length=12)),
            ],
        ),
    ]
